version: 2
jobs:
  node:
    working_directory: ~/search-bar
    docker:
      - image: circleci/node:7.4.0
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      # - save_cache:
      #     key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      #     paths:
      #       - ~/.cache/yarn

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

    
    